# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-04 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(null=True, upload_to='uploadedimages'),
        ),
    ]
