# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userid',
        ),
    ]
